"""Lab plotting utilities (style + reusable figure helpers + hot-wire analysis)."""

# Lightweight symbols first (avoids Jupyter / partial-import issues with ``NU_AIR``).
from .constants import CALIBRATED_VELOCITY_DATASET, NU_AIR
from .settings.standard import set_font, set_ticks_sig
from .style import (
    FLOW_COLORS,
    PDF_COLORS,
    finalize_figure,
    save_figure,
    subplots,
    use_lab_matplotlib_style,
)
from . import hotwire
from .hotwire import (
    CalibratedVelocity,
    CalibrationFit,
    collect_calibration_voltage_pitot_means,
    compute_normalized_spectrum_run,
    dissipation_epsilon,
    dissipation_from_time_derivatives,
    epsilon_from_welch_spectrum,
    find_dataset_by_leaf,
    fit_kolmogorov_reference_line,
    fit_voltage_to_velocity_poly,
    integral_length_scale_longitudinal,
    kolmogorov_length,
    kolmogorov_velocity,
    load_calibrated_hotwire_velocity,
    load_first_group_pitot_and_hotwire_voltage,
    markdown_row,
    print_spectrum_markdown_tables,
    resolve_spectrum_legend_label,
    spectrum_estimator_label,
    taylor_microscale_from_epsilon,
    taylor_microscale_from_series,
    velocity_series_to_e11_spectrum,
    welch_spectrum_for_epsilon,
    write_pitot_calibrated_hotwire_h5,
)
from .plots.hotwire import (
    plot_calibration_scatter_and_fit,
    plot_hotwire_velocity_pdf,
    plot_pitot_vs_calibrated_hotwire,
    plot_tke_spectrum_kolmogorov_normalized,
)

__all__ = [
    "CALIBRATED_VELOCITY_DATASET",
    "FLOW_COLORS",
    "NU_AIR",
    "PDF_COLORS",
    "CalibratedVelocity",
    "CalibrationFit",
    "collect_calibration_voltage_pitot_means",
    "compute_normalized_spectrum_run",
    "dissipation_epsilon",
    "dissipation_from_time_derivatives",
    "epsilon_from_welch_spectrum",
    "finalize_figure",
    "find_dataset_by_leaf",
    "fit_kolmogorov_reference_line",
    "fit_voltage_to_velocity_poly",
    "hotwire",
    "integral_length_scale_longitudinal",
    "kolmogorov_length",
    "kolmogorov_velocity",
    "load_calibrated_hotwire_velocity",
    "load_first_group_pitot_and_hotwire_voltage",
    "markdown_row",
    "plot_calibration_scatter_and_fit",
    "plot_hotwire_velocity_pdf",
    "plot_pitot_vs_calibrated_hotwire",
    "plot_tke_spectrum_kolmogorov_normalized",
    "print_spectrum_markdown_tables",
    "resolve_spectrum_legend_label",
    "save_figure",
    "set_font",
    "set_ticks_sig",
    "spectrum_estimator_label",
    "subplots",
    "taylor_microscale_from_epsilon",
    "taylor_microscale_from_series",
    "use_lab_matplotlib_style",
    "velocity_series_to_e11_spectrum",
    "welch_spectrum_for_epsilon",
    "write_pitot_calibrated_hotwire_h5",
]
